version: "3.8"
services:
  accommodation:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb-accommodation
  mongodb-accommodation:
    image: mongo
    container_name: mongodb-accommodation
    ports:
      - 28017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express-accommodation:
    image: mongo-express
    container_name: mongo-express-accommodation
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb-accommodation
volumes:
  data: {}

networks:
  default:
    name: service-discovery_default